SHIP_WARBIRD = 0
SHIP_JAVELIN = 1
SHIP_SPIDER = 2
SHIP_LEVIATHAN = 3
SHIP_TERRIER = 4
SHIP_WEASEL = 5
SHIP_LANCASTER = 6
SHIP_SHARK = 7
SHIP_SPECTATOR = 8
SHIP_NONE = SHIP_SPECTATOR

SHIP_NAMES = {
    SHIP_WARBIRD: 'Warbird',
    SHIP_JAVELIN: 'Javelin',
    SHIP_SPIDER: 'Spider',
    SHIP_LEVIATHAN: 'Leviathan',
    SHIP_TERRIER: 'Terrier',
    SHIP_WEASEL: 'Weasel',
    SHIP_LANCASTER: 'Lancaster',
    SHIP_SHARK: 'Shark',
    SHIP_SPECTATOR: 'Spectator'
}
